on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello World action step
      id: hello
      uses: qinkeith/my-project@v1
      with: 
        who-to-greet: 'keith'
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"